"""
Django settings for mgp project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uar27mxamnh!_2(97q2fwzci82wcs8a*kh3(lnwon+hm#9l&$z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
VERSION_API = 'version-1'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'units',
    'common',
    'products',
    'purchase_orders',
    'transactions',
    'conclusion',
    'mgpAPI',
    'oauth2_provider',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'mgp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mgp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'mgp_test',
        'ENGINE': 'sqlserver',
        'HOST': 'localhost',
        'USER': 'sa',
        'PASSWORD': 'passwOrd',
        'OPTIONS': {
            'provider': 'SQLNCLI11',
            'use_legacy_date_fields': True,
        }
    },
    'mgp_erp': {
        'NAME': 'TPC_270315',
        'ENGINE': 'sqlserver',
        'HOST': 'localhost',
        'USER': 'sa',
        'PASSWORD': 'passwOrd',
        'OPTIONS': {
            'provider': 'SQLNCLI11',
            'use_legacy_date_fields': True,
        }

    }

}

# 'mgp_erp': {
#         'NAME': 'TPC_270315',
#         'ENGINE': 'sqlserver',
#         'HOST': 'localhost',
#         'USER': 'sa',
#         'PASSWORD': 'passwOrd',
#         'OPTIONS': {
#             'provider': 'SQLNCLI11',
#             'use_legacy_date_fields': True,
#         }
#
#     }
# }
#
# 'mgp_erp': {
#     'NAME': 'TPC Power Holding Public Company Limited',
#     'ENGINE': 'sqlserver',
#     'HOST': '172.20.10.9',
#     'USER': 'jak',
#     'PASSWORD': 'P@ssw0rd',
#     'OPTIONS': {
#         'provider': 'SQLNCLI11',
#         'use_legacy_date_fields': True,
#     }
#
# }

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'mydatabase',
        },
        'mgp_erp': {
            'NAME': 'TPC_270315',
            'ENGINE': 'sqlserver',
            'HOST': 'localhost',
            'USER': 'sa',
            'PASSWORD': 'passwOrd',
            'OPTIONS': {
                'provider': 'SQLNCLI11',
                'use_legacy_date_fields': True,
            }
        }

    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'mgp',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#            "init_command": "SET default_storage_engine=INNODB",
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
