# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-18 22:36
from __future__ import unicode_literals

from django.db import migrations
from common.master_models import Preference
from units.models import UnitCategory


def load_pref(apps, schema_editor):
    Preference.objects.create(key='steam_factor', value=3.6)


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0004_auto_20170707_2026'),
    ]

    operations = [
        migrations.RunPython(load_pref)

    ]
