# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 16:25
from __future__ import unicode_literals

from django.db import migrations
from mgpAPI.erp_services.syn_all import syncall


def load_unit(apps, schema_editor):
    unit_all = apps.get_model("units", "UnitCategory")

    unit_all(title='unit all', description='unit all'
           ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_unit)
    ]