# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170702_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustdetail',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_adjustdetail_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adjustdetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputdetail',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_inputdetail_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputdetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='returndetail',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_returndetail_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returndetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapdetail',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_scrapdetail_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrapdetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_transaction_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_transactionlog_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawdetail',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_withdrawdetail_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawdetail',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
