# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20170908_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdetail',
            name='line_no',
        ),
        migrations.AddField(
            model_name='withdrawdetail',
            name='erp_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawdetail',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Sector'),
        ),
    ]
