# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170909_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawdetail',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
