# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_withdrawdetail_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputjuntionadjust',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier'),
        ),
        migrations.AlterField(
            model_name='inputjuntionreturn',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier'),
        ),
        migrations.AlterField(
            model_name='inputjuntionscrap',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier'),
        ),
        migrations.AlterField(
            model_name='inputjuntionwithdraw',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier'),
        ),
    ]
