# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20170920_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustdetail',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputdetail',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returndetail',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawdetail',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
