# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20171017_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustdetail',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='inputdetail',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='returndetail',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='scrapdetail',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='withdrawdetail',
            name='internal',
        ),
    ]
