# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20171017_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustdetail',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputdetail',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returndetail',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawdetail',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
    ]
