# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20171214_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='erp_no',
            field=models.IntegerField(default=0),
        ),
    ]
