# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_erp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawdetail',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
