# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_withdrawdetail_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdetail',
            name='reserve_quantity',
            field=models.FloatField(default=0),
        ),
    ]
