# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-02 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_inputdetail_reserve_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdetail',
            name='used',
        ),
    ]
