# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingtransactionline',
            old_name='received_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='manufacturingtransactionline',
            name='used_quantity',
        ),
    ]
