# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0002_auto_20170702_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
