# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0003_auto_20170702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingtransaction',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_manufacturingtransaction_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtransaction',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtransactionline',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_manufacturingtransactionline_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtransactionline',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='outage',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_outage_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outage',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_powergeneration_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
