# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0005_auto_20170707_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powergeneration',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Sector'),
        ),
    ]
