# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conclusion', '0007_auto_20170924_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumtion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumtion',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_consumtion_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumtion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumtion',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='consumtion',
            name='last_modified_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_consumtion_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
