# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0008_auto_20170924_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumtion',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='consumtion',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='consumtion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='consumtion',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='consumtion',
            name='last_modified_users',
        ),
    ]
