# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20171017_2030'),
        ('conclusion', '0009_auto_20170926_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingtransactionline',
            name='withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.WithdrawDetail'),
        ),
    ]
