# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0010_manufacturingtransactionline_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingtransactionline',
            name='withdraw',
        ),
    ]
