# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
        ('common', '0002_auto_20170628_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('po', models.CharField(max_length=255)),
                ('posting_date', models.DateTimeField()),
                ('soft_delete', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_purchaseorder_objects', to=settings.AUTH_USER_MODEL)),
                ('last_modified_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_purchaseorder_objects', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivered', models.IntegerField(choices=[(0, 'Opened'), (1, 'Partial'), (2, 'Delivered')], default=0)),
                ('line_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('outstanding_quantity', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(default=0)),
                ('soft_delete', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_purchaseorderline_objects', to=settings.AUTH_USER_MODEL)),
                ('last_modified_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_purchaseorderline_objects', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchase_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.PurchaseOrder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Supplier')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
