# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_auto_20170707_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='last_modified_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_purchaseorder_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='last_modified_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_purchaseorderline_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
