# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
