# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170716_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
