# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171024_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
